"cluster_name": "ghost-k3d"
"created_at": "2026-01-15T19:35:36Z"
"ingress_class": "modules/networking/ingress-class.yaml"
"ip_ranges":
  "metallb":
  - "172.18.255.200-172.18.255.250"
  "services":
  - "172.18.255.100-172.18.255.199"
"metallb_config": "modules/networking/metallb-config.yaml"
"network_name": "ghost-k3d-network"
"service_ips": "modules/networking/service-ips.yaml"
