# Loki Logging Stack Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/dmitri166/ghost_on_prem_project
    targetRevision: master
    path: platform/manifests/logging
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.namespace
          value: logging-new
  destination:
    server: https://kubernetes.default.svc
    namespace: logging-new
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10
