"created_at": "2026-01-15T19:35:36Z"
"environment": "dev"
"stack":
  "alertmanager":
    "enabled": true
    "version": "v0.27.0"
  "grafana":
    "admin_user": "admin"
    "enabled": true
    "version": "10.2.0"
  "loki":
    "enabled": true
    "version": "latest"
  "opentelemetry":
    "enabled": true
    "version": "latest"
  "prometheus":
    "enabled": true
    "retention": "15d"
    "version": "v2.45.0"
  "tempo":
    "enabled": true
    "version": "latest"
