"created_at": "2026-01-15T19:35:36Z"
"environment": "dev"
"storage_classes":
- "is_default_class": true
  "name": "local-path"
  "parameters": {}
  "provisioner": "rancher.io/local-path"
  "reclaim_policy": "Delete"
  "volume_binding_mode": "WaitForFirstConsumer"
- "is_default_class": false
  "name": "fast-ssd"
  "parameters": {}
  "provisioner": "rancher.io/local-path"
  "reclaim_policy": "Delete"
  "volume_binding_mode": "Immediate"
